name: (PR) Auto Assign Author

on:
  push:
    branches:
      - 'test/**'

permissions:
  pull-requests: write

jobs:
  assign-author:
    runs-on: self-hosted
    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
