name: Code Analyzing

on:
  push:
    branches:
      - 'test/**'

jobs:
  detekt_analyzer:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
          cache: 'gradle'

      - name: 'Run Detekt analyzer'
        run: ./gradlew --no-daemon :notifications:detekt

  code_build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
          cache: 'gradle'

      - name: 'Run code build'
        run: ./gradlew --no-daemon assembleRelease
