name: Publish

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
          cache: gradle
          working-directory: ./android

      - name: Decode keystore
        id: decode-keystore
        run: |
          echo "${{ secrets.JKS_FILE }}" > release.jks.asc
          gpg --batch --passphrase "${{ secrets.JKS_STORE_PASSPHRASE }}" -d -o release.jks app/release.jks.asc

      - name: Decode GPG private key
        id: decode-key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d

      - name: Publish All Artifacts
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          GPG_KEY: ${{ steps.decode-key.outputs.stdout }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}

        run:
          ./gradlew publishAllPublicationsToSonatypeStagingRepository
