name: Publish

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    environment: maven-conf
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 19
          cache: gradle

      - name: Decode GPG private key
        id: decode-key
        run: echo "${{ secrets.SIGN_KEY }}" | base64 -d

      - name: Publish All Artifacts
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          SIGN_KEY: ${{ steps.decode-key.outputs.stdout }}
          SIGN_KEY_ID: ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY_PASS: ${{ secrets.SIGN_KEY_PASS }}

        run:
          ./gradlew publishAllPublicationsToSonatypeStagingRepository
